package _McDonaldsCorbaPackage;


/**
* _McDonaldsCorbaPackage/_McDonaldsCorbaImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/corba/McDonaldsCorba.idl
* Segunda-feira, 2 de Junho de 2014 22h22min27s BRT
*/

public abstract class _McDonaldsCorbaImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements _McDonaldsCorbaPackage.McDonaldsCorba, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _McDonaldsCorbaImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("produceMcChicken", new java.lang.Integer (0));
    _methods.put ("consumeMcChicken", new java.lang.Integer (1));
    _methods.put ("getQtdMcChicken", new java.lang.Integer (2));
    _methods.put ("getQtdMcChickenConsumers", new java.lang.Integer (3));
    _methods.put ("getQtdMcChickenProducers", new java.lang.Integer (4));
    _methods.put ("produceMcFish", new java.lang.Integer (5));
    _methods.put ("consumeMcFish", new java.lang.Integer (6));
    _methods.put ("getQtdMcFish", new java.lang.Integer (7));
    _methods.put ("getQtdMcFishConsumers", new java.lang.Integer (8));
    _methods.put ("getQtdMcFishProducers", new java.lang.Integer (9));
    _methods.put ("produceBigMac", new java.lang.Integer (10));
    _methods.put ("consumeBigMac", new java.lang.Integer (11));
    _methods.put ("getQtdBigMac", new java.lang.Integer (12));
    _methods.put ("getQtdBigMacConsumers", new java.lang.Integer (13));
    _methods.put ("getQtdBigMacProducers", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // _McDonaldsCorbaPackage/McDonaldsCorba/produceMcChicken
       {
         this.produceMcChicken ();
         out = $rh.createReply();
         break;
       }

       case 1:  // _McDonaldsCorbaPackage/McDonaldsCorba/consumeMcChicken
       {
         this.consumeMcChicken ();
         out = $rh.createReply();
         break;
       }

       case 2:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcChicken
       {
         int $result = (int)0;
         $result = this.getQtdMcChicken ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcChickenConsumers
       {
         int $result = (int)0;
         $result = this.getQtdMcChickenConsumers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcChickenProducers
       {
         int $result = (int)0;
         $result = this.getQtdMcChickenProducers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // _McDonaldsCorbaPackage/McDonaldsCorba/produceMcFish
       {
         this.produceMcFish ();
         out = $rh.createReply();
         break;
       }

       case 6:  // _McDonaldsCorbaPackage/McDonaldsCorba/consumeMcFish
       {
         this.consumeMcFish ();
         out = $rh.createReply();
         break;
       }

       case 7:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcFish
       {
         int $result = (int)0;
         $result = this.getQtdMcFish ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcFishConsumers
       {
         int $result = (int)0;
         $result = this.getQtdMcFishConsumers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdMcFishProducers
       {
         int $result = (int)0;
         $result = this.getQtdMcFishProducers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 10:  // _McDonaldsCorbaPackage/McDonaldsCorba/produceBigMac
       {
         this.produceBigMac ();
         out = $rh.createReply();
         break;
       }

       case 11:  // _McDonaldsCorbaPackage/McDonaldsCorba/consumeBigMac
       {
         this.consumeBigMac ();
         out = $rh.createReply();
         break;
       }

       case 12:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdBigMac
       {
         int $result = (int)0;
         $result = this.getQtdBigMac ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 13:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdBigMacConsumers
       {
         int $result = (int)0;
         $result = this.getQtdBigMacConsumers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 14:  // _McDonaldsCorbaPackage/McDonaldsCorba/getQtdBigMacProducers
       {
         int $result = (int)0;
         $result = this.getQtdBigMacProducers ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:McDonaldsCorbaPackage/McDonaldsCorba:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _McDonaldsCorbaImplBase
