package _McDonaldsCorbaPackage;

/**
* _McDonaldsCorbaPackage/McDonaldsCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/corba/McDonaldsCorba.idl
* Segunda-feira, 2 de Junho de 2014 22h22min27s BRT
*/

public final class McDonaldsCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public _McDonaldsCorbaPackage.McDonaldsCorba value = null;

  public McDonaldsCorbaHolder ()
  {
  }

  public McDonaldsCorbaHolder (_McDonaldsCorbaPackage.McDonaldsCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _McDonaldsCorbaPackage.McDonaldsCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _McDonaldsCorbaPackage.McDonaldsCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _McDonaldsCorbaPackage.McDonaldsCorbaHelper.type ();
  }

}
