package _McDonaldsCorbaPackage;


/**
* _McDonaldsCorbaPackage/McDonaldsCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/corba/McDonaldsCorba.idl
* Segunda-feira, 2 de Junho de 2014 22h22min27s BRT
*/

public interface McDonaldsCorbaOperations 
{
  void produceMcChicken ();
  void consumeMcChicken ();
  int getQtdMcChicken ();
  int getQtdMcChickenConsumers ();
  int getQtdMcChickenProducers ();
  void produceMcFish ();
  void consumeMcFish ();
  int getQtdMcFish ();
  int getQtdMcFishConsumers ();
  int getQtdMcFishProducers ();
  void produceBigMac ();
  void consumeBigMac ();
  int getQtdBigMac ();
  int getQtdBigMacConsumers ();
  int getQtdBigMacProducers ();
} // interface McDonaldsCorbaOperations
