package _McDonaldsCorbaPackage;


/**
* _McDonaldsCorbaPackage/McDonaldsCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/main/java/corba/McDonaldsCorba.idl
* Segunda-feira, 2 de Junho de 2014 22h22min27s BRT
*/

public interface McDonaldsCorba extends McDonaldsCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface McDonaldsCorba
